### ISSUE TITLE
How to expire token on logout button ?

### ISSUE THREAD

**Issue by shashanksmf** [RobDWaller/ReallySimpleJWT#10] opened 2018-04-01 18:31 UTC

**Comment by Qocotzxin** [comment] 2018-04-02 12:12
You can just delete it from local/session Storage with clear().

**Comment by shashanksmf** [comment] 2018-04-02 13:00
Agree but how that can be done on server side because the token is still valid on the server side.
In short how to invalidate the token on server side.

**Comment by Kryten0807** [comment] 2018-04-19 20:43
There is no way to invalidate a JWT token. The best you can do is keep a list on your server of the tokens you have issued and reject any that are not in your list. Then, if a user signs out, remove that token from your list.

**Comment by RobDWaller** [comment] 2018-05-01 14:08
Sorry I should have responded to this thread sooner, I've been a little busy, apologies. As @Kryten0807 says you can store a list on your server if you choose and delete them when they are no longer needed.

Alternatively you can use the expiry date and trade existing tokens for new tokens. For instance if you set an expiry date of one hour, after 59 minutes you ask the server for a new token. The old token then expires naturally and you use the new token for another 59 minutes.

**Comment by RobDWaller** [comment] 2018-05-08 15:37
I'm going to close this issue as I think the issue is resolved.

**Closed by RobDWaller** 2018-05-08 15:37 UTC
Labels: question
